version: '3'

services:
  php:
    container_name: sample_php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
    - ./src:/var/www

  nginx:
    image: nginx
    container_name: sample_nginx
    ports:
    - 80:80
    volumes:
    - ./src:/var/www
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php

  db:
    image: mysql:8.0
    # platform: linux/x86_64 # M1の場合はコメントアウトをはずす
    container_name: sample_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
    - 4306:3306

volumes:
  npm-cache:
    driver: local
